# Generated by Django 3.1.4 on 2020-12-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='purchase_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supply_number',
        ),
    ]
