# Generated by Django 3.1.4 on 2020-12-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_key', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('custmng', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prvdmng', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prodmng', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mantmng', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('muluser', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('statrpt', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
