# Generated by Django 3.1.4 on 2020-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20201221_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(blank=True, choices=[('default', 'Light'), ('cosmic', 'Cosmic'), ('dark', 'Dark'), ('corporate', 'Corporate')], max_length=10, null=True),
        ),
    ]
