# Generated by Django 3.1.4 on 2020-12-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_licence_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='basic_key',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='mulstor',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='licence',
            name='encryption_key',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
